set ts=2
set et
set ai
autocmd FileType gitcommit setlocal spell textwidth=72 "set up highlighting on your commits to show you where the 50 character limit for the subject and the longer 72 character limit for subsequent lines in the commit end
au BufNewFile,BufRead *.yaml,*.yml so ~/.vim/yaml.vim
let g:jedi#auto_initialization = 1
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup
set laststatus=2 " Always display the statusline in all windows
set showtabline=2 " Always display the tabline, even if there is only one tab
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
set t_Co=256
